export const topcisList=[
    "web",
  "machinelearning ",
  "cloud",
  "graphics",
  "education",
  "datascience ",
  "webdevelopment ",
  "security",
  "compilers",
  "programminglanguages ",
  "visualization",
  "mobile",
  "robotics",
  "science",
  "datavisualization ",
  "webapplications ",
  "networking",
  "realtime ",
  "bigdata ",
  "operatingsystems ",
  "ai",
  "computervision ",
  "database",
  "simulation",
  "bioinformatics",
  "video",
  "virtualization",
  "databases",
  "desktop",
  "deeplearning ",
  "developertools ",
  "hardware",
  "kernel",
  "artificialintelligence ",
  "audio",
  "communication",
  "embeddedsystems ",
  "linux",
  "naturallanguage processing ",
  "distributedsystems ",
  "genomics",
  "iot",
  "research",
  "community",
  "data",
  "mathematics",
  "real-time",
  "scientificcomputing ",
  "algorithms",
  "automation",
  "cross-platform",
  "developmenttools ",
  "devops",
  "games",
  "highperformance computing ",
  "media",
  "monitoring",
  "multimedia",
  "operatingsystem ",
  "userinterface ",
  "webapplication ",
  "3d",
  "communications",
  "compiler",
  "drivers",
  "embedded",
  "imageprocessing ",
  "opendata ",
  "physics",
  "programminglanguages and development tools ",
  "testing",
  "2d/3dgraphics ",
  "astronomy",
  "collaboration",
  "containers",
  "dataanalytics ",
  "gis",
  "health",
  "library",
  "nlp",
  "opensource ",
  "optimization",
  "packagemanagement ",
  "privacy",
  "programming",
  "programmingtools ",
  "routing",
  "scientificvisualization ",
  "streaming",
  "virtualreality ",
  "vision",
  "webapps ",
  "api",
  "biology",
  "buildtools ",
  "chat",
  "cloudcomputing ",
  "dataanalysis ",
  "debugging",
  "engineering",
  "fpga",
  "functionalprogramming ",
  "instantmessaging ",
  "kubernetes",
  "libraries",
  "maps",
  "music",
  "openhardware ",
  "openscience ",
  "programminglanguage ",
  "scienceand medicine ",
  "statistics",
  "tools",
  "ui",
  "videoprocessing ",
  "accessibility",
  "apis",
  "computationalbiology ",
  "concurrency",
  "dataprocessing ",
  "datavisualisation ",
  "design",
  "digitalsignal processing ",
  "encryption",
  "framework",
  "geospatial",
  "high-performancecomputing ",
  "ide",
  "internetof things ",
  "messaging",
  "network",
  "nonprofit",
  "packagemanagers ",
  "python",
  "rendering",
  "search",
  "semanticweb ",
  "softwaredefined radio ",
  "sql",
  "storage",
  "webservices ",
  "android",
  "animation",
  "applications",
  "astrophysics",
  "automotive",
  "c++",
  "civictech ",
  "cloudnative ",
  "cms",
  "dataintegration ",
  "datamining ",
  "data-science",
  "email",
  "emulation",
  "enduser application ",
  "firmware",
  "functional-programming",
  "fuzzing",
  "gameengines ",
  "gui",
  "informationsecurity ",
  "infrastructure",
  "javascript",
  "language",
  "linearalgebra ",
  "machinetranslation ",
  "mapping",
  "math",
  "mathematicalsoftware ",
  "metrics",
  "middleware",
  "mobileapps ",
  "mobile-apps",
  "networkanalysis ",
  "numericalcomputation ",
  "numericalcomputing ",
  "packaging",
  "performance",
  "realtime",
  "reverseengineering ",
  "runtimesystems ",
  "signalprocessing ",
  "softwaredefined networking ",
  "softwareengineering ",
  "staticcode analysis‎ ",
  "vr",
  "webplatform and services ",
  "appdevelopment ",
  "application",
  "applicationsecurity ",
  "apps",
  "browser",
  "bugfinding ",
  "buildsystems ",
  "camera",
  "cheminformatics",
  "citizenscience ",
  "clouddatabases ",
  "codeanalysis ",
  "compression",
  "computernetworking ",
  "contentmanagement ",
  "continuousdelivery ",
  "continuousintegration ",
  "datadiscovery ",
  "datamanagement ",
  "datastructures ",
  "desktopenvironment ",
  "development",
  "disassembly",
  "distributed",
  "distributedcomputing ",
  "distributednetworks ",
  "documentation",
  "dsp",
  "editing",
  "editor",
  "edtech",
  "enduser applications ",
  "environment",
  "formalmethods ",
  "forum",
  "game",
  "gamedevelopment ",
  "gaming",
  "geoinformatics",
  "geometry",
  "globalhealth ",
  "graphics/ video / audio / virtual reality ",
  "greatdeveloper tooling ",
  "hpc",
  "humanitarian",
  "imageanalysis ",
  "internet",
  "java",
  "knowledgegraphs ",
  "logging",
  "metadata",
  "microservices ",
  "microservices",
  "mobileapplications ",
  "networksecurity ",
  "neuroscience",
  "observability",
  "offline",
  "packagemanager ",
  "parallelcomputing ",
  "precisionmedicine ",
  "privacy/security",
  "programanalysis ",
  "realtimecommunications ",
  "rust",
  "sandbox",
  "socialgood ",
  "softwareanalysis ",
  "space",
  "standards",
  "systemprogramming ",
  "teaching",
  "teamchat ",
  "tooling",
  "tracing",
  "ui/ux",
  "verification",
  "versioncontrol ",
  "videodecode ",
  "visualprogramming ",
  "voip",
  "vpn",
  "webapps",
  "wiki",
  "wireless",
  "workflows",
  "#compilers",
  "#education",
  "#functional-programming",
  "#programming-languages",
  "#programming-tools",
  "AI/ML",
  "BIOS",
  "Neuralnetworks ",
  "SearchEngines ",
  "WebRTC",
  "academicprojects ",
  "algorithmprototyping/visualization ",
  "analytics",
  "apimanagement ",
  "architecture",
  "art",
  "audioanalysis ",
  "audioprocessing ",
  "backend",
  "bigdata visualization ",
  "biochemistry",
  "blockchain",
  "books",
  "bot",
  "c++tools ",
  "cad",
  "cancer",
  "cancerresearch ",
  "chatops",
  "cli",
  "cloudinfrastructure ",
  "codegeneration ",
  "codingstandards ",
  "commandline ",
  "communicationsengineering ",
  "compliance",
  "computationgeometry ",
  "computationalchemistry ",
  "computationalgeometry ",
  "computationallinguistics ",
  "computersecurity ",
  "configurationmanagement ",
  "container",
  "crowdsourcing",
  "cryptography",
  "cubesats",
  "culturalheritage ",
  "cybersecurity",
  "dataand databases ",
  "dataextraction ",
  "dataprocessing pipeline ",
  "datasharing ",
  "debug",
  "decentralization",
  "decentralized",
  "declarativelanguage ",
  "decompilation",
  "dependencies",
  "desktopapplication ",
  "desktopapplications ",
  "desktopintegration ",
  "devtools",
  "distributeddatabases ",
  "distribution",
  "drones",
  "dsl",
  "earthobservation ",
  "eclipse",
  "educationaltechnology ",
  "ehealth",
  "electronicdesign tools ",
  "embeddded",
  "embeddedhardware ",
  "enterprise",
  "enterpriseapplication ",
  "enterpriseapplications ",
  "faas",
  "fastalgorithms ",
  "featuredetection ",
  "filesystems",
  "filmmaking",
  "frameworks",
  "freeand open source software ",
  "freesoftware ",
  "front-end",
  "frontend",
  "fullstack web and mobile ",
  "geo",
  "geolocation",
  "git",
  "googlecloud ",
  "government",
  "gpu",
  "graphs",
  "groupchat ",
  "hfoss",
  "highperformance ",
  "highperformance data processing ",
  "http",
  "humanlanguage technologies ",
  "imaging",
  "industry",
  "informationretrieval ",
  "inputmethods ",
  "interactivity",
  "internetfreedom ",
  "interoperability",
  "ipv6",
  "json",
  "knowledgegraph ",
  "learning",
  "learningmanagement ",
  "legal",
  "licensecompliance ",
  "license-scan",
  "licensing",
  "linguistics",
  "linkeddata ",
  "linter",
  "linuxdistribution ",
  "livestreaming ",
  "logic",
  "lowlevel",
  "macos",
  "mail",
  "massspectrometry ",
  "mechanics",
  "medicalimaging ",
  "medicalrecords ",
  "medicine",
  "mesh",
  "mobiledevelopment ",
  "mobileprogramming ",
  "modeling",
  "multimodalcommunication ",
  "musicengraving ",
  "naturallanguage understanding ",
  "navigation",
  "networkbiology ",
  "networkmonitoring ",
  "networkprogramming ",
  "networksimulation ",
  "networks",
  "nonprofits",
  "numericaland data analysis software ",
  "numericalmethods ",
  "objectoriented programming ",
  "object-oriented",
  "openeducation ",
  "osslicensing ",
  "packagesystem ",
  "parallelalgorithms ",
  "parser",
  "perception",
  "performanceoptimization ",
  "photography",
  "php",
  "platform",
  "pointclouds ",
  "polyglot",
  "productivity",
  "programmerproductivity ",
  "programminglibraries ",
  "programming-tools",
  "radiology",
  "realtime communications ",
  "realtimecommunication ",
  "realtimemessaging ",
  "reinforcementlearning ",
  "reproducibility",
  "ros",
  "rtos",
  "scanning",
  "securedevelopment ",
  "server",
  "servicemesh ",
  "simulations",
  "slam",
  "soc",
  "social",
  "socialimpact ",
  "softwaredevelopment ",
  "softwarequality ",
  "softwaretesting ",
  "spaceapplications ",
  "spdx",
  "sre",
  "storagesystems ",
  "subtitles",
  "systems",
  "systemsbiology ",
  "systemsprogramming ",
  "texteditor ",
  "timeseries ",
  "toolchain",
  "tv",
  "userexperience ",
  "ux",
  "vectorgraphics ",
  "vfx",
  "videoencode ",
  "virtualmachine ",
  "visualisation",
  "vulnerabilities",
  "webapplication security ",
  "webcommunity ",
  "webprogramming ",
  "webservers ",
  "wifi",
  "wikipedia",
  "windows",
  "wirelesscommunications ",
  "wirelessnetworks ",
  "xr",
  "2dacceleration ",
  "2danimation ",
  "360stereo video ",
  "3DReconstruction ",
  "3Ddata processing ",
  "3Dmachine learning ",
  "3Dvisualization ",
  "3dacceleration ",
  "3danimation ",
  "3dcad geometry ",
  "3dcomputer vision ",
  "3dprinting ",
  "3dtools ",
  "3dui",
  "AIML",
  "APITesting ",
  "AR",
  "ASICdesign ",
  "ApplicationDevelopment ",
  "Authentication",
  "AuthoritativeDNS software ",
  "AutomatedTesting ",
  "Backup",
  "Benchmark",
  "CAM",
  "CI/CD",
  "Chatplatform ",
  "Checkpoint/Restore",
  "Circumvention",
  "CloudNative",
  "Codec",
  "CommunicationProtocols ",
  "DL-inference",
  "DNSrecursive solutions ",
  "DTLS",
  "DXP",
  "DataMeshes ",
  "Datacataloging ",
  "DatabaseEngines ",
  "Databasesystems ",
  "DevTool ",
  "DevSecOps",
  "DiversityEquity and Inclusion ",
  "Drone",
  "EcologicalForecasting, ",
  "EdgeAI ",
  "Effects",
  "ElectronicMedical Record System ",
  "EmbeddedSystem ",
  "Fairness",
  "Film",
  "Flashcards",
  "Fortran",
  "FunctionalTesting ",
  "Geoinformation",
  "HDL",
  "History",
  "HumanRights ",
  "IAM",
  "IMDG",
  "IPcores ",
  "In-memory",
  "Inclusive",
  "Interpretibility",
  "JIT",
  "Jingle",
  "License",
  "Logicbugs ",
  "Massivecommunity ",
  "Mockand Stubs Generation ",
  "Modelling",
  "MulitmodelData ",
  "Multi-agentSystems ",
  "Musicrecommendation ",
  "Neuronavigation",
  "Nocode platform ",
  "NoSQLDatabase ",
  "OS",
  "OpenSource Bioinformatics ",
  "OperationalAnalytics ",
  "Operations",
  "Packages",
  "PerformanceOptimisation ",
  "PersonalServer ",
  "Processor",
  "Programming& Build Tools ",
  "PythonMLOps Framework ",
  "QAautomation ",
  "RISC-V",
  "Real-TimeCommunication ",
  "Robustness",
  "SAT& SMT solving ",
  "SBOM",
  "SDR",
  "SQLFeatures ",
  "Safety",
  "SecureMessaging ",
  "SecurityCryptography ",
  "SecurityDefense ",
  "Serverdevelopment ",
  "ServerlessComputing ",
  "Software-DefinedRadio ",
  "Software-Defined-Storage",
  "SoftwareCompositionAnalysis",
  "Sound",
  "StandardLibraries ",
  "Structuralengineering ",
  "Surveillance",
  "Systemon Chip ",
  "TLS",
  "TeamCollaboration ",
  "ThreatIntelligence ",
  "UGV",
  "UX/UI",
  "VectorDatabase ",
  "VisualEffects ",
  "academia",
  "academicresearch ",
  "acceleratedmedia ",
  "accesibility",
  "acoustics",
  "acpi",
  "actormodel ",
  "administrator",
  "aerodynamics",
  "aeroelasticity",
  "aerogear",
  "aeronautics",
  "aerospace",
  "agent",
  "alerting",
  "alerts",
  "algorithmics",
  "analysis",
  "analyzing",
  "android-sdk",
  "angularjs",
  "anonymity",
  "anti-censorship",
  "apidescription ",
  "appsec",
  "archive",
  "archiving",
  "arrangement",
  "artisttools ",
  "assembly",
  "ast",
  "async",
  "asynchronous",
  "asynchronousmany task systems ",
  "asynchronousmanytask systems ",
  "atomicphysics ",
  "audioeditor ",
  "audiofirmware ",
  "authorization",
  "automatedprogram repair ",
  "automobile",
  "autonomousvehicle ",
  "autopilot",
  "backups",
  "beacons",
  "beatdetection",
  "benchmarking",
  "bibtex",
  "bigcode ",
  "bigdata science ",
  "bigproject ",
  "bigdata",
  "binarytools ",
  "bio/neuroimage processing ",
  "bioinformtics",
  "biologicalnetworks ",
  "biomedicaldata science ",
  "biomedicalinformatics ",
  "biophysics",
  "bittorrent",
  "blindness",
  "bookmarking",
  "bootloader ",
  "bootloader",
  "bots",
  "braille",
  "brainimaging ",
  "brainmodeling ",
  "brainmodelling ",
  "brainsimulation ",
  "bsd",
  "c",
  "c++development ",
  "c++libraries c++ standard ",
  "c++standard ",
  "c++standardizaion ",
  "c++standardization ",
  "c-c+ ",
  "cad/cam/cae",
  "callibration",
  "cancerinformatics ",
  "cars",
  "cartography",
  "censorship",
  "ceph",
  "cfc",
  "charity",
  "chatbot",
  "checkpoint-restore",
  "chemistry",
  "chiplets",
  "ci",
  "cinematography",
  "civic",
  "civictechnology ",
  "civic-tech",
  "civilsociety ",
  "climatemonitoring ",
  "climatescience ",
  "clinical",
  "clinics",
  "clojure",
  "cloudnative java ",
  "cloudsecurity ",
  "cloudstorage ",
  "cloudwith google computer engine ",
  "cloud-native",
  "cluster",
  "clustering",
  "co-speechgesture ",
  "codeanalysis and spdx ",
  "codeconversion ",
  "codequality ",
  "codereview tool ",
  "codescan and matching ",
  "codecs",
  "codeuino",
  "codingconventions ",
  "cognitiveradio ",
  "cognitivescience ",
  "colormanagement ",
  "combinatorics",
  "communicationsystem ",
  "communityarchitecture ",
  "communitybuilding ",
  "communityhealth ",
  "communityscience ",
  "compatibility",
  "compilation",
  "compilerapi ",
  "complianceautomation ",
  "component-baseddevelopment ",
  "components",
  "composing",
  "compress",
  "compressio",
  "computationgraph ",
  "computationalmechanics ",
  "computationalphotography ",
  "computational-chemistry",
  "computeralgebra ",
  "computerarchitecture ",
  "computergraphics ",
  "computer-aidedtranslation ",
  "computer-assistedtranslation ",
  "conference",
  "conferences",
  "configu",
  "contacts&calendarsync ",
  "containerskubernetes ",
  "contributoractivity ",
  "conversational",
  "conversionstandards ",
  "convexoptimization ",
  "coprocessing",
  "copyleft",
  "copyright",
  "corpusannotation ",
  "counter-censorship",
  "crawling",
  "creativecoding ",
  "creativecommons ",
  "creativitytools ",
  "crm",
  "crossdesktop ",
  "crossplatform ",
  "cseducation ",
  "cubesat",
  "culture",
  "customization",
  "cybersecurity ",
  "datafusion ",
  "datamodeling ",
  "dataportal ",
  "datarefinement ",
  "datasecurity ",
  "datastreaming ",
  "datavizualisation ",
  "data-collection",
  "data-intensivescience ",
  "databaseoptimization ",
  "databaseservices ",
  "dataviz",
  "ddd",
  "debian-ci",
  "debuggers",
  "decentralisation",
  "decentralised",
  "deception",
  "decoder",
  "deep-learning",
  "dependencymanagement ",
  "designsystem ",
  "deskstop",
  "dev-ops",
  "developer",
  "developingcountries ",
  "developingworld ",
  "devices",
  "dhcp",
  "diagnostic",
  "diagnostics",
  "dicompathology ",
  "differentialprivacy ",
  "digitaldesign ",
  "digitalfinancial services ",
  "digitalforensics ",
  "digitalhardware design ",
  "digitalimaging ",
  "digitalknowledge ",
  "digitallibrary ",
  "digitallogic design ",
  "digitalpreservation ",
  "digitalrights ",
  "digitization",
  "directx",
  "discovery",
  "display",
  "distributeddatastructures ",
  "distributedenergy systems ",
  "distributedsystem ",
  "diversity",
  "diversityand inclusion ",
  "diy",
  "dj",
  "django",
  "dns",
  "docker",
  "docs",
  "drupal8 ",
  "dvcs",
  "dynamicenvironment ",
  "e-health",
  "e-learning",
  "e-mail",
  "e2e",
  "earthdata ",
  "earthscience ",
  "earthsciences ",
  "earth-systemmonitoring ",
  "ecologicalforecasting ",
  "ecosystemmodels ",
  "eda",
  "edatools ",
  "edge",
  "edit",
  "edk2",
  "electromagnetics",
  "electronicmedical records ",
  "electronicvoting ",
  "electronics",
  "electrophysiology",
  "eletricmobility ",
  "embeddablewidget ",
  "embedded/automotive",
  "emulator",
  "encoding",
  "encryptedcomputation ",
  "encyclopedia",
  "end-userapplication ",
  "energy",
  "engines",
  "engraving",
  "entepriseanalytics ",
  "enterpriseinformation systems ",
  "environmentgeneration ",
  "eventhandling ",
  "eventmanagement ",
  "eventsolutions ",
  "evented",
  "eventsmanagement ",
  "exoplanet",
  "exploitation",
  "extensions",
  "fake-news",
  "fashiontech",
  "federated",
  "federatedlearning ",
  "federation",
  "ffi",
  "ffmpegneuronetwork ",
  "fileformats ",
  "fileshare ",
  "filesystem",
  "filter",
  "finance",
  "financialinclusion ",
  "finitestate automata ",
  "fintech",
  "firefox",
  "firewall",
  "firmwaredevelopment ",
  "flashchips ",
  "flashcard",
  "floatingcar data ",
  "floss",
  "fonts",
  "food",
  "foreignfunction interface ",
  "forensic",
  "frameworkdevelopment ",
  "freeand open source software  license and origin ",
  "free-speech",
  "fullstack ",
  "functionprogramming language ",
  "functionalsafety ",
  "fundraising",
  "futureinternet architecture ",
  "gamedesign ",
  "gameengine ",
  "gametheory ",
  "generalpurpose os ",
  "generativeAI ",
  "generativetext ",
  "genetics",
  "genome",
  "genomeassembly ",
  "geocoding",
  "geoinformationsystems ",
  "geometryprocessing ",
  "geophysics",
  "geoprocessing",
  "geostatistics",
  "gesture",
  "github",
  "global",
  "globaldevelopment ",
  "globalhealth and development ",
  "globaloptimization ",
  "gnss",
  "gnu",
  "googleearth ",
  "gpucomputing ",
  "grammar",
  "graphalgorithms ",
  "graphicstack ",
  "graphicsstack ",
  "graphicsuser interface ",
  "graphql",
  "groundpenetrating radar ",
  "gtk",
  "guitoolkit ",
  "guitar",
  "hardwareaccelerated media processing ",
  "haskell",
  "healthcare",
  "highenergy astrophysics ",
  "highquality codebase ",
  "high-energyastrophysics ",
  "high-energyphysics ",
  "high-performancedata processing ",
  "high-performance-computing",
  "homeservers ",
  "hometheater ",
  "homebrew",
  "honeynet",
  "honeynets",
  "honeypot",
  "honeypots",
  "hospitals",
  "hosting",
  "hotspot",
  "hpx",
  "humanrights",
  "hydra",
  "hypervisor",
  "hypervisorintrospection ",
  "i18n",
  "ictd",
  "identity",
  "iio",
  "ike",
  "ikev2",
  "illustration",
  "image",
  "imageprcessing ",
  "imagesynthesis ",
  "images",
  "inmemory data grid ",
  "in-memorydata grid ",
  "inclusion",
  "inclusivity",
  "indexing",
  "individualprojects ",
  "inference",
  "informationtheory ",
  "informationccentric networking ",
  "init",
  "initsystems ",
  "instrumentation",
  "integrateddevelopment environments ",
  "integration",
  "integrations",
  "interactive",
  "interfaces",
  "international",
  "internetaccess ",
  "internetcensorship ",
  "ionmobility ",
  "ios",
  "iot& edge ",
  "iotcps ",
  "ipc",
  "ipfs",
  "ipsec",
  "ipsecvpn ",
  "javajsp ",
  "javaee",
  "journalism",
  "jvm",
  "kernelscripting ",
  "kinematics",
  "knowledgeextraction ",
  "knowledgerepresentation ",
  "landrights ",
  "landsystem modelling ",
  "languageserver ",
  "languagetechnology ",
  "languagetechology ",
  "languages",
  "latex",
  "law",
  "lawand policy ",
  "less-resourcedlanguages ",
  "less-resourceslanguages ",
  "lesser-resourcedlanguages ",
  "level",
  "licensemanagement ",
  "licensing& software quality QA ",
  "lifesciences ",
  "lightweight",
  "linktime optimization ",
  "linuxkernel ",
  "literature",
  "livemigration ",
  "liveprogramming ",
  "loadtesting ",
  "load-balancing",
  "localgrammars ",
  "locationtech",
  "lod",
  "logmanagement ",
  "lowlevel programming ",
  "lsb",
  "macos x ",
  "machine",
  "machinetrans ",
  "machine-to-machine",
  "mailinglists ",
  "makers",
  "malware",
  "malwareanalysis ",
  "malware-analysis",
  "mappingand surveying ",
  "martech",
  "materialdesign ",
  "materials",
  "materialsscience ",
  "matlab",
  "mechanicalengineering ",
  "mediaacceleration ",
  "mediaanalysis ",
  "mediacenter ",
  "mediadatabase ",
  "mediamanagement ",
  "mediaserver ",
  "media-analytics",
  "mediawiki",
  "medicalpractice management solution ",
  "medicalrecord ",
  "medicalresearch ",
  "medicalsimulation ",
  "membershipmanagement ",
  "meshgeneration ",
  "meshprocessing ",
  "mesh-networks",
  "messagecorrelation ",
  "messagequeue ",
  "mhealth",
  "micro-services",
  "microfinance",
  "microkernel",
  "microscopy",
  "midi",
  "migration",
  "minecraft",
  "minifier",
  "misinformation",
  "missioncontrol ",
  "ml-inference",
  "mlearning",
  "mobileapp ",
  "mobilebanking ",
  "mobilerobots ",
  "mobilesecurity ",
  "mobilestreaming ",
  "modding",
  "modelchecking ",
  "modeling& optimization ",
  "molecularanalysis ",
  "moleculardynamics ",
  "molecularnetworking ",
  "molecularsimulation ",
  "molecular-simulation",
  "montecarlo methods ",
  "morphologicalanalysis ",
  "motionplanning ",
  "movies",
  "mozilla",
  "multi-agentsystem ",
  "multibodydynamics ",
  "multicloud",
  "multicore",
  "multilinguallanguage resources ",
  "multilinguality",
  "multimediaretrieval ",
  "multimodality",
  "multiphysics",
  "musicinformation retrieval ",
  "musicnotation ",
  "musicsocial network ",
  "musicxml",
  "mvc",
  "mysql",
  "naturebased solutions ",
  "neighbor-search",
  "networkautomation ",
  "networkmanagement system ",
  "networkmapping ",
  "networkstorage ",
  "networkvisualization ",
  "neuralnetwork ",
  "neuralsearch ",
  "neuroimageprocessing ",
  "neuroimaging",
  "newprojects ",
  "news-media",
  "next-generationsequencing ",
  "nodered",
  "non-linear",
  "non-profit",
  "nonblocking",
  "nosql",
  "notation",
  "notationsoftware ",
  "note-taking",
  "notes",
  "object-orientedprogramming ",
  "offensivesecurity ",
  "office",
  "officesuite ",
  "offlineaccess ",
  "ogc",
  "ogcstandards ",
  "omicsdata ",
  "on-devicemachine learning ",
  "ontologies",
  "openevent ",
  "opengovernment ",
  "opensource medical records ",
  "opensource software metrics ",
  "openstandards ",
  "opensystem firmware ",
  "openweb ",
  "opendata",
  "opengl",
  "openmp",
  "openshift",
  "opensource",
  "opensourceaudio firmware ",
  "opentype",
  "operatingsystem developer tools ",
  "operating-system",
  "optimisation",
  "orbitaldynamics ",
  "orbitalmechanics ",
  "osscompliance ",
  "osslicencing ",
  "other",
  "p2p",
  "package",
  "packageand dependencies licensing and origin ",
  "packagevulnerabilities and security ",
  "parallel",
  "parallelism",
  "parallelization",
  "partialdifferential equations ",
  "particlephysics ",
  "pdf",
  "peacecorps ",
  "pedagogy",
  "peerfeedback ",
  "peerto peer ",
  "peer-reviewedlibraries ",
  "penetrationtesting ",
  "pentesting",
  "perl",
  "personalassistants ",
  "pharmacologicalmodeling ",
  "philosophy",
  "physicalcomputing ",
  "physicallybased rendering ",
  "physiology",
  "piano",
  "pipelineautomation ",
  "playback",
  "plotting",
  "plottingtools ",
  "pointset processing ",
  "pollution",
  "polyhedralcompilation ",
  "polyhedralmodel ",
  "polystore",
  "populationgenetics ",
  "portable",
  "posix",
  "postgresql",
  "pragrammerproductivity ",
  "precisionhealth ",
  "printing",
  "probabilisticmodels ",
  "processautomation ",
  "processordesign ",
  "profiling",
  "programverification ",
  "programming-language",
  "progressiveweb apps ",
  "project-management",
  "pronunciation",
  "publiccode ",
  "pydata",
  "qa",
  "quantumchemistry ",
  "radar",
  "radiativetransfer ",
  "rails",
  "railsapplication ",
  "raredisease ",
  "raytracing ",
  "rdbms",
  "react",
  "reactive",
  "reactivelanguages ",
  "reactiveprogramming ",
  "realunix ",
  "real-timecomputer graphics ",
  "real-timeos ",
  "real-timesystem ",
  "real-time-communications",
  "referencemanager ",
  "relationaldatabase ",
  "reliablelog transfer ",
  "remoteaccess ",
  "remotepatient monitoring ",
  "remotesensing ",
  "remote-access",
  "researchand development ",
  "restapis ",
  "resultpresentation ",
  "retrieval",
  "reverse-engineering",
  "robot",
  "robotperception ",
  "robotsimulator ",
  "roboticssimulation ",
  "routingprotocols ",
  "rovers",
  "ruby",
  "runtimes",
  "saas",
  "samba",
  "satellitedata ",
  "save/restore",
  "scalability",
  "schoolapps ",
  "schoolsystem ",
  "schoolsystems ",
  "scienceand enineering ",
  "scraping",
  "scratch",
  "screenreader ",
  "scripting",
  "scriptinglanguages ",
  "sdlc",
  "sdn",
  "seamless",
  "securityand privacy ",
  "securityand software bill of materials ",
  "self-hosted",
  "selfdriving",
  "semantics",
  "sensorweb ",
  "sensors",
  "sensorweb",
  "sepsisdetection ",
  "sepsisprediction ",
  "sharing",
  "sheetmusic ",
  "silicon",
  "simulationsoftware ",
  "simulators",
  "sip",
  "smartcities ",
  "smartcontracts ",
  "smtsolver ",
  "snapshots",
  "socialscience ",
  "social-network",
  "softmatter physics ",
  "softreal-time ",
  "soft-matter-physics",
  "software",
  "softwareanalytics ",
  "softwarearcheology ",
  "softwareas a service ",
  "softwarecomposition analysis ",
  "softwareconfigurability ",
  "softwaredefined storage ",
  "softwaremodel checking ",
  "softwarepackages ",
  "softwarepreservation ",
  "softwareradio ",
  "softwarereuse ",
  "softwaresustainability ",
  "softwareverification ",
  "softwarevisualization ",
  "software-definednetworking ",
  "solarphysics ",
  "solidgeometry ",
  "solidmodeling ",
  "solver",
  "sourcecode analyzer ",
  "sourcecode archive ",
  "sourcecode management ",
  "spacestandards ",
  "spacecraft",
  "spamfiltering ",
  "spatial",
  "spatialdata ",
  "spatialdata infrastructures ",
  "spatialinformation ",
  "spatialinformation infrastructures ",
  "spectrumanalysis ",
  "speechrecognition ",
  "stateful",
  "statisticalcomputing ",
  "stem",
  "storageserver ",
  "streamprocessing ",
  "structureddata ",
  "structuredtransparency ",
  "supernova",
  "sustainability",
  "symbolicexecution ",
  "symbolicmathematics ",
  "symfony",
  "sync",
  "synchronisation",
  "synchronized",
  "syscall",
  "systemmodelling ",
  "system-on-chip",
  "systers",
  "tc39",
  "tcp",
  "teachingquality codebase ",
  "team",
  "technicalcomputing ",
  "telecom",
  "telecommunications",
  "telephony",
  "television",
  "tensorflow",
  "terminalapplications ",
  "testinput generation ",
  "testing/ci",
  "textanalytics ",
  "textediting ",
  "textgeneration ",
  "textto speech ",
  "time-series",
  "timeseries",
  "toolbox",
  "toolboxframeworks ",
  "toolchains",
  "top10 ",
  "trajectoryanalysis ",
  "trajectoryanalytics ",
  "trajectorygeneration ",
  "transcoding",
  "triangulation",
  "triangulaton",
  "truetype",
  "typesystem ",
  "typesystems ",
  "uav",
  "uefi",
  "uidesign ",
  "uitoolkit ",
  "unifiedAPI ",
  "unikernels",
  "unittesting ",
  "unix",
  "unmannedvehicle ",
  "unopionated",
  "unrealengine ",
  "upstream",
  "usabilty",
  "usergenerated content ",
  "userinterface components ",
  "userland",
  "verificationof concurrent systems ",
  "version-control",
  "videoapis ",
  "videocapture ",
  "videoconferencing ",
  "videodecoding/encoding ",
  "videoediting ",
  "videoframework ",
  "videoplayer ",
  "videopost processing ",
  "vim",
  "virtualmachines ",
  "vison",
  "visualdesign ",
  "visualizationgrammar ",
  "voice",
  "voiceapps ",
  "voiceassistants ",
  "voxel",
  "vulkan",
  "webarchives ",
  "webarchiving ",
  "webarchving ",
  "webbrowser ",
  "webextensions ",
  "webperformance ",
  "webportal ",
  "webprocessing ",
  "webtechnologies ",
  "web-basedgeoprocessing ",
  "web-interface",
  "webhook",
  "webvr",
  "wikimedia",
  "windowmanagement ",
  "windowsystem ",
  "windowingsystem ",
  "windowingsystems ",
  "wireguard",
  "wirelesscommunication ",
  "womenin open source ",
  "womenin tech ",
  "xmpp",
  "zephyr",
  "zero-downtime"
]
export const technologiesList=[ "python",
  "javascript",
  "c",
  "c++",
  "java",
  "android",
  "react",
  "html",
  "node.js",
  "golang",
  "linux",
  "postgresql",
  "rust",
  "opengl",
  "css",
  "mysql",
  "machinelearning ",
  "php",
  "ruby",
  "qt",
  "go",
  "docker",
  "python3 ",
  "django",
  "typescript",
  "git",
  "tensorflow",
  "ios",
  "sql",
  "cmake",
  "kubernetes",
  "perl",
  "rubyon rails ",
  "lua",
  "angular",
  "reactjs",
  "rest",
  "c++11",
  "kotlin",
  "assembly",
  "html5",
  "llvm",
  "opencv",
  "web",
  "gtk",
  "shellscript ",
  "deeplearning ",
  "elasticsearch",
  "github",
  "mongodb",
  "ros",
  "scala",
  "angularjs",
  "cloud",
  "cython",
  "jupyter",
  "linuxkernel ",
  "r",
  "raspberrypi ",
  "shell",
  "vulkan",
  "webdevelopment ",
  "xml",
  "arduino",
  "cpp",
  "cuda",
  "fpga",
  "jquery",
  "jvm",
  "networking",
  "pytorch",
  "swift",
  "ai",
  "arm",
  "artificialintelligence ",
  "c#",
  "c++17",
  "flask",
  "flutter",
  "haskell",
  "kvm",
  "numpy",
  "qt5",
  "virtualization",
  "vue.js",
  "x86",
  "asm",
  "bash",
  "bigdata ",
  "c++14",
  "computervision ",
  "d3",
  "dataanalysis ",
  "ffmpeg",
  "gis",
  "grpc",
  "hadoop",
  "html5/css3",
  "julia",
  "lisp",
  "opencl",
  "postgres",
  "reactnative ",
  "sqlite",
  "verilog",
  "webrtc",
  "xmpp",
  "ansible",
  "apachespark ",
  "clang",
  "compiler",
  "datascience ",
  "databases",
  "distributedsystems ",
  "embedded",
  "erlang",
  "gpu",
  "gradle",
  "grafana",
  "graphql",
  "gstreamer",
  "gtk+",
  "highperformance computing ",
  "javafx",
  "jenkins",
  "json",
  "kernel",
  "make",
  "medicalimaging ",
  "posix",
  "qemu",
  "rdf",
  "risc-v",
  "scripting",
  "spring",
  "unix",
  "vhdl",
  "windows",
  "xen",
  "antlr",
  "audio",
  "autotools",
  "aws",
  "boost",
  "bootstrap",
  "bsdunix ",
  "c99",
  "chisel",
  "clojure",
  "containers",
  "elixir",
  "fortran",
  "gcc",
  "gnumake ",
  "googleapp engine ",
  "groovy",
  "gwt",
  "ide",
  "microservices",
  "midi",
  "mobile",
  "mpi",
  "nlp",
  "numba",
  "ocaml",
  "openhardware ",
  "openmp",
  "pandas",
  "prometheus",
  "pythondeep learning frameworks ",
  "qml",
  "r-project",
  "redis",
  "robotics",
  "sdr",
  "spark",
  "swig",
  "symfony",
  "vala",
  "video",
  "vue",
  "wayland",
  "webservices ",
  "webassembly",
  "win32",
  ".net",
  "Jax",
  "apachekafka ",
  "api",
  "assembler",
  "atom",
  "awk",
  "beam",
  "bigdata science ",
  "blender",
  "browserextension ",
  "bsd",
  "bytecode",
  "clanguage ",
  "cprogramming ",
  "c++libraries c++11 c++14 c++17 c++20 ",
  "c++20",
  "c/c+",
  "caffe",
  "ci",
  "cms",
  "concurrency",
  "d3.js",
  "dart",
  "database",
  "deeplearning",
  "devops",
  "dicom",
  "dsp",
  "electron",
  "elk",
  "elm",
  "embeddedsystems ",
  "emberjs",
  "fhir",
  "filesystems",
  "functionalprogramming ",
  "gazebo",
  "geospatial",
  "gnuautotools ",
  "gnu/linux",
  "googlecloud ",
  "graph",
  "hardwareacceleration ",
  "iot",
  "jruby",
  "kafka",
  "luarocks",
  "machinelearning",
  "mariadb",
  "materialui",
  "matlab",
  "meteor.js",
  "micro-services",
  "middleware",
  "neo4j",
  "networkstack ",
  "nextflow",
  "nltk",
  "nosql",
  "ogcstandards ",
  "openapi",
  "openwrt",
  "openxr",
  "osx",
  "parallelalgorithms ",
  "prolog",
  "rails",
  "real-time",
  "restfulapi ",
  "rpc",
  "scikit-learn",
  "singularity",
  "sphinx",
  "svg",
  "systemverilog",
  "tcl",
  "videocodecs ",
  "vision",
  "visualization",
  "waf",
  "webgl",
  "webpack",
  "wxwidgets",
  "x11",
  "xpath",
  "#js",
  "#jvm",
  "#llvm",
  "#scala",
  "#scala_lang",
  "ASIC",
  "Akka",
  "AsyncAPI",
  "Bison",
  "Blockchain",
  "C++template metaprogramming ",
  "C/Rust/Go",
  "Chromium",
  "Codec",
  "Cryptography",
  "Cypress",
  "DNS",
  "DRM",
  "Data-Science",
  "Django+PostgreSQL",
  "Emscripten",
  "Flatpak",
  "GEGL",
  "Ghidra",
  "Git/GitHub",
  "GoogleEarth ",
  "Graphics",
  "Hardware",
  "Helm",
  "Imaging",
  "JSONSchema ",
  "JuiceShop ",
  "MERN",
  "MachineLearning ",
  "Media",
  "MultimodelAI ",
  "Multiplatform",
  "Netty",
  "NextJs",
  "OAuth",
  "OIDC",
  "ObjectiveC ",
  "Open-RMF",
  "OpenCASCADE",
  "OpenInventor",
  "OpenStreetMap",
  "OpenTelemetry",
  "POSIXshell ",
  "Parsers& Compilers ",
  "Processor",
  "RFCs",
  "RISCV",
  "React-Native",
  "Rxjava",
  "SBOM",
  "SCSS",
  "SUnit",
  "Serverless",
  "TLS",
  "Technicalwriting ",
  "Testing",
  "VLSI",
  "VST",
  "Vtk",
  "VueJS",
  "XR",
  "ZAP",
  "ZephyrRTOS ",
  "a-frame",
  "advanceddata structures ",
  "aerogear",
  "airflow",
  "ajax",
  "android/ios",
  "angular.js",
  "apacheairflow ",
  "apachearrow ",
  "apis",
  "app",
  "archc",
  "arrow",
  "asciidoctor",
  "asm/c/c++",
  "asr",
  "assemblylanguage ",
  "asynchronousi/o ",
  "audioprocesing ",
  "audioprocessing ",
  "automatedreasoning ",
  "automaton",
  "automotive",
  "babel",
  "backend",
  "batman",
  "bazel",
  "beacon",
  "beacons",
  "beaglebone",
  "bibtex",
  "bigquery",
  "bioinformatics",
  "biojs",
  "bios",
  "bluetooth",
  "boinc",
  "bpm",
  "breakpad",
  "browserextensions ",
  "bsdmake ",
  "buildbot",
  "bundler",
  "c++17parallel stl ",
  "cabal",
  "cad",
  "cakephp",
  "canvas",
  "cassandra",
  "celery",
  "ceph",
  "cesium",
  "cesiumjs",
  "chapel",
  "chatbots",
  "che",
  "ci/cd",
  "cifs",
  "clojurescript",
  "cocoa",
  "codecs",
  "codeworld",
  "communicationprotocol ",
  "compilers",
  "component-baseddevelopment ",
  "compression",
  "configurationmanagement ",
  "containerorchestration ",
  "contentmanagement system ",
  "coq",
  "couchdb",
  "cross-platform",
  "crossplatform",
  "css3",
  "cups",
  "céu",
  "d",
  "d3js",
  "dart/flutter",
  "dash",
  "dask",
  "data",
  "datastructures ",
  "datproject",
  "ddos",
  "decentralisation",
  "decode",
  "dhcp",
  "differentialprivacy ",
  "directx",
  "distributedcomputing ",
  "dlang",
  "documentation",
  "dpdk",
  "drones",
  "drupal",
  "drupal8 ",
  "dtrace",
  "ebpf",
  "eclipse",
  "eclipsejavaide",
  "eiffel",
  "elasicsearch",
  "electromobility",
  "email",
  "ember",
  "encode",
  "envoy",
  "epbf",
  "espresso",
  "euslisp",
  "event-loop",
  "f#",
  "fasm",
  "fastfluid dynamics ",
  "federatedlearning ",
  "finite-statetechnologies ",
  "firewall",
  "firmware",
  "flatassembler ",
  "fluentd",
  "fonts",
  "fossology",
  "framework",
  "free/netbsd",
  "frontend",
  "fsts",
  "fuzzing",
  "gamedevelopment ",
  "gawk",
  "gcp",
  "gdal",
  "gdscript",
  "geo",
  "ghc",
  "github-actions",
  "gitops",
  "glib",
  "gnss",
  "gnupg",
  "gobject",
  "golan",
  "googleweb toolkit ",
  "graphite",
  "gtkmm",
  "gui",
  "guile",
  "guix",
  "hg",
  "hibernate",
  "hid",
  "hiddenmarkov models ",
  "high-resolutiontimers ",
  "hl7fhir ",
  "homomorphicencryption ",
  "honeypot",
  "honeypots",
  "hpc",
  "hpx",
  "htcvive ",
  "html5canvas ",
  "htop",
  "http/2",
  "hydra",
  "hyperledgeraries ",
  "hypervisor",
  "i386",
  "i586",
  "iaccessible2",
  "ice- zeroc ",
  "ida-pro",
  "ignition",
  "illumos",
  "influxdb",
  "instrumentation",
  "integerset library ",
  "internationalization",
  "internetof things ",
  "ionic",
  "ipp",
  "irc",
  "isabelleproof assistant ",
  "isl",
  "jakarta",
  "jakartaee",
  "javaee ",
  "javacc",
  "javasc",
  "javascr",
  "jinja2",
  "jni",
  "jsonapi ",
  "json/json-ld",
  "jsonnet",
  "juce",
  "julialang",
  "junit",
  "jupyternotebook ",
  "kconfig",
  "keras",
  "kibana",
  "kms",
  "kustomize",
  "lamp",
  "language-agnostic",
  "latex",
  "leaflet",
  "lede/openwrt",
  "lfe",
  "library",
  "libusb",
  "libuv",
  "libxcam",
  "linkerd",
  "linuxdistribution ",
  "lunatik",
  "lwgjl",
  "lwjgl",
  "lxc",
  "macos",
  "manymore ",
  "mapping",
  "mapsapi ",
  "matlab/simulink",
  "mbed",
  "mediawiki",
  "memory",
  "mercurial",
  "meson",
  "meteorJS",
  "micropython",
  "milp",
  "mips",
  "ml",
  "mlir",
  "mobil",
  "models",
  "mongo",
  "mp4",
  "mp4box",
  "mqtt",
  "multi-core",
  "multi-threading",
  "multimedia",
  "multimodalanalysis ",
  "music",
  "namedentity recognition ",
  "namespaces",
  "naturallanguage processing ",
  "net",
  "netbsd",
  "nix",
  "nss",
  "nt",
  "object-oriented",
  "object-storage",
  "oceanscience ",
  "oceantechnology ",
  "olsr",
  "ontologies",
  "opensource databases ",
  "open-sound-control",
  "openhrp",
  "openj9",
  "openpgp",
  "openrtm",
  "openscenegraph",
  "opentracing",
  "opentype",
  "openvpn",
  "openzfs",
  "operatingsystems ",
  "operator",
  "ordbms",
  "ortelius",
  "os",
  "pallene",
  "parallelprocessing ",
  "parallelization",
  "patroni",
  "pcap",
  "pcl",
  "pencil",
  "perl5",
  "perl6",
  "pharo",
  "physicalcomputing ",
  "physicalweb ",
  "pixhawk",
  "polly",
  "polymath",
  "polymer",
  "postgis",
  "ppcg",
  "programminglanguages ",
  "programming-language",
  "protobuf",
  "protocolbuffers ",
  "pthon",
  "pygame",
  "pyqt",
  "pyth",
  "pythongtk ",
  "rdbms",
  "react.js",
  "reactive",
  "reactiveextensions ",
  "reactjsjavascript ",
  "reactnative",
  "redux",
  "regularexpressions ",
  "remoteaccess ",
  "restapi ",
  "rf",
  "roassal",
  "rom",
  "ros/gazebo",
  "routing",
  "rpm",
  "rspec",
  "rtos",
  "rubyon rail ",
  "rubygems",
  "sanitizers",
  "scalanative ",
  "scala.js",
  "scalability",
  "scheme",
  "science",
  "scilab",
  "screwdriver",
  "screwdriver.cd",
  "sdl",
  "search",
  "securemulti-party computation ",
  "security",
  "selenium",
  "semanticweb ",
  "servant",
  "server",
  "servicemesh ",
  "simd",
  "sip",
  "skala",
  "smalltalk",
  "smb",
  "smt",
  "smtsolvers ",
  "soa",
  "sockets",
  "softwaredefined radio ",
  "softwareradio ",
  "solr",
  "some/ip",
  "soundopen firmware ",
  "spaceapplications ",
  "sparql",
  "spec",
  "spi",
  "spinnaker",
  "spir-v",
  "sql/nosql",
  "sqlalchemy",
  "squeak",
  "ssh",
  "standards",
  "staticanalysis ",
  "statistics",
  "streaming",
  "subtitles",
  "supercollider",
  "svelte",
  "syntaxnet",
  "synthesis",
  "sysstat",
  "systemonchip",
  "tcl/tk",
  "tcp",
  "tekton",
  "templates",
  "terminal-kit",
  "terraform",
  "textmining ",
  "tla+",
  "tokio_rs",
  "torch",
  "twig",
  "twisted",
  "uefi",
  "uiautomation ",
  "ui/ux",
  "unicode",
  "unrealengine ",
  "v4l2",
  "va-api",
  "vaapi",
  "vectors",
  "vega",
  "vega-lite",
  "velocity",
  "vim",
  "virtuoso",
  "visualstudio ",
  "voctomix",
  "vpp",
  "webapplication firewall ",
  "webapps ",
  "webbluetooth ",
  "webasssembly",
  "webcomponents",
  "webgpu",
  "webkit",
  "webs",
  "wiki",
  "win32api ",
  "wordpress",
  "workflows",
  "x86assembly ",
  "xarray",
  "xcode",
  "xia",
  "xilinx",
  "xtext",
  "yocto",
  "zerocice ",
  "zeromq",
  "zfs",
  "zmq",
  "zope"
]